syntax = "proto3";

package agdesigns.elevatefitness.shared.grpc;

import "google/protobuf/timestamp.proto";
import "google/protobuf/empty.proto";

option java_package = "agdesigns.elevatefitness.shared.grpc";

// Workout data synced via DataStore
message WorkoutStaticData {
  int64 workout_id = 1;
  google.protobuf.Timestamp start_date = 2;
  repeated Exercise exercises = 3;
  repeated float suggested_tares = 6;
  DefaultIncrements default_increments = 7;
  bool imperial_system = 8;
  bool active_workout = 9;
  float previous_intensity = 10;
  repeated ProtoSuggestedModification suggested_modifications = 11;
}

message ProtoSuggestedModification {
  bool hasSuggestion = 1;
  ProtoModificationType type = 2;
  string targetExerciseName = 3; // empty if no target
}

enum ProtoModificationType {
    EXERCISE_ADDED = 0;
    EXERCISE_SKIPPED = 1;
    EXERCISE_REPLACED = 2;
}

message WorkoutDynamicData {
  repeated SuggestedRepsWeight suggested_reps_weight = 4;
  repeated int32 sets_done = 5;
}

message Exercise {
  int64 workout_exercise_id = 1;
  int64 program_exercise_id = 2;
  string name = 3;
  string equipment = 4;
  int32 orderInProgram = 5;
  repeated int32 reps = 6;
  repeated int32 rest = 7;
  string note = 8;
  string variation = 9;
  int64 superset_exercise = 10;
  bool is_duration_based = 11;
}

message SuggestedRepsWeight {
  repeated string reps = 1;
  repeated string weight = 2;
}

message DefaultIncrements {
  float bodyweight = 1;
  float barbell = 2;
  float dumbbell = 3;
  float machine = 4;
  float cable = 5;
}

// Set completed from watch to be sent to phone
message SetCompleted {
  int64 workout_id = 1;
  int64 exercise_id = 2;
  int32 reps = 3;
  float weight = 4;
  float tare = 5;
  int64 rest = 6;
  google.protobuf.Timestamp rest_timestamp = 7;
}

message SetCompletedResponse {
  bool success = 1;
  string message = 2;
}

message WorkoutActiveResponse {
  bool active = 1;
}

message CompleteWorkout {
  float intensity = 1;
  float calories = 2;
  int32 max_heart_rate = 3;
  int32 avg_heart_rate = 4;
  int32 min_heart_rate = 5;
  repeated int32 heart_rates = 6;
}

message AcceptedModification {
  int32 exercise_index = 1;
}

// gRPC service for events
service WorkoutService {
  rpc workoutActive(google.protobuf.Empty) returns (WorkoutActiveResponse);
  rpc setCompleted(SetCompleted) returns (SetCompletedResponse);
  rpc completeWorkout(CompleteWorkout) returns (google.protobuf.Empty);
  rpc acceptModification(AcceptedModification) returns (google.protobuf.Empty);
}

message ExerciseToScrollTo {
  int32 exercise_index = 1;
}

// set completed from phone; to be sent to watch for rest keeping
message RestPhone2Watch {
  int64 rest = 1;
  google.protobuf.Timestamp rest_timestamp = 2;
}

// used by phone to tell watch stuff
service WorkoutWearService {
  // TODO: merge scrollToExercise into set rest, scroll to exercise should be a
  //  side effect of a set completed on phone
  rpc scrollToExercise(ExerciseToScrollTo) returns (google.protobuf.Empty);
  rpc setRest(RestPhone2Watch) returns (google.protobuf.Empty);
  // stops workout on watch
  rpc stopWorkout(google.protobuf.Empty) returns (google.protobuf.Empty);
  rpc getHealthData(google.protobuf.Empty) returns (CompleteWorkout);
}