syntax = "proto3";

package agdesigns.elevatefitness.shared.grpc;

import "google/protobuf/timestamp.proto";
import "google/protobuf/empty.proto";

option java_package = "agdesigns.elevatefitness.shared.grpc";

// Workout data synced via DataStore
message WorkoutStaticData {
  int64 workout_id = 1;
  google.protobuf.Timestamp start_date = 2;
  repeated Exercise exercises = 3;
  repeated float suggested_tares = 6;
  DefaultIncrements default_increments = 7;
  bool imperial_system = 8;
  bool active_workout = 9;
  float previous_intensity = 10;
  repeated ProtoSuggestedModification suggested_modifications = 11;
  bool smart_features_in_rest_hints = 12;
  bool smart_features_tempo_rom_tracking = 13;
}

message ProtoSuggestedModification {
  bool hasSuggestion = 1;
  ProtoModificationType type = 2;
  string targetExerciseName = 3; // empty if no target
  // these are not really needed but help to make the object unique
  int64 targetId = 4;
  int64 sourceId = 5;
}

enum ProtoModificationType {
    EXERCISE_ADDED = 0;
    EXERCISE_SKIPPED = 1;
    EXERCISE_REPLACED = 2;
}

message WorkoutDynamicData {
  repeated SuggestedRepsWeight suggested_reps_weight = 4;
  repeated int32 sets_done = 5;
}

enum WearRepTrackable {
  NOT_TRACKABLE = 0;
  ROTATION_MOVEMENT = 1;
  SUPPORTED = 2;
}

enum FirstPhase {
  AGAINST_GRAVITY = 0;
  ALONG_GRAVITY = 1;
  PARALLEL = 2;
}

message Exercise {
  int64 workout_exercise_id = 1;
  int64 program_exercise_id = 2;
  string name = 3;
  string equipment = 4;
  int32 orderInProgram = 5;
  repeated int32 reps = 6;
  repeated int32 rest = 7;
  string note = 8;
  string variation = 9;
  int64 superset_exercise = 10;
  bool is_duration_based = 11;
  repeated string set_types = 12;
  WearRepTrackable wear_rep_trackable = 13;
  FirstPhase first_phase = 14;
  int64 exercise_id = 15;  // only used to link exercise to Tempo/ROM tracking params
}

message SuggestedRepsWeight {
  repeated string reps = 1;
  repeated string weight = 2;
}

message DefaultIncrements {
  float bodyweight = 1;
  float barbell = 2;
  float dumbbell = 3;
  float machine = 4;
  float cable = 5;
}

message ProtoRepMetrics {
  int32 index = 1;
  int64 concentric_ms = 2;
  int64 eccentric_ms = 3;
  float range_of_motion_m = 4;
  float peak_velocity = 5;
}

message ProtoSetTrackingResult {
  bool data_available = 1;
  int32 detected_reps = 2;
  int32 reported_reps = 3;
  int64 avg_concentric_ms = 4;
  int64 avg_eccentric_ms = 5;
  float avg_range_of_motion_m = 6;
  repeated ProtoRepMetrics reps = 7;
}

// Set completed from watch to be sent to phone
message SetCompleted {
  int64 workout_id = 1;
  int64 exercise_id = 2;
  int32 reps = 3;
  float weight = 4;
  float tare = 5;
  int64 rest = 6;
  google.protobuf.Timestamp rest_timestamp = 7;
  ProtoSetTrackingResult setTracking = 8;
}

message SetCompletedResponse {
  bool success = 1;
  string message = 2;
}

message WorkoutActiveResponse {
  bool active = 1;
}

message CompleteWorkout {
  float intensity = 1;
  float calories = 2;
  int32 max_heart_rate = 3;
  int32 avg_heart_rate = 4;
  int32 min_heart_rate = 5;
  repeated int32 heart_rates = 6;
}

message AcceptedModification {
  int32 exercise_index = 1;
}

message AddSetRequest {
  int64 workout_id = 1;
  int64 exercise_id = 2;
}

message ExtendRestRequest {
  int64 additional_seconds = 1;
}

// gRPC service for events
service WorkoutService {
  rpc workoutActive(google.protobuf.Empty) returns (WorkoutActiveResponse);
  rpc setCompleted(SetCompleted) returns (SetCompletedResponse);
  rpc completeWorkout(CompleteWorkout) returns (google.protobuf.Empty);
  rpc acceptModification(AcceptedModification) returns (google.protobuf.Empty);
  rpc addSet(AddSetRequest) returns (google.protobuf.Empty);
  rpc extendRest(ExtendRestRequest) returns (google.protobuf.Empty);
}

message ExerciseToScrollTo {
  int32 exercise_index = 1;
}

// set completed from phone; to be sent to watch for rest keeping
message RestPhone2Watch {
  int64 rest = 1;
  google.protobuf.Timestamp rest_timestamp = 2;
}

// used by phone to tell watch stuff
service WorkoutWearService {
  // TODO: merge scrollToExercise into set rest, scroll to exercise should be a
  //  side effect of a set completed on phone
  rpc scrollToExercise(ExerciseToScrollTo) returns (google.protobuf.Empty);
  rpc setRest(RestPhone2Watch) returns (google.protobuf.Empty);
  // stops workout on watch
  rpc stopWorkout(google.protobuf.Empty) returns (google.protobuf.Empty);
  rpc getHealthData(google.protobuf.Empty) returns (CompleteWorkout);
}